export const language = {
    Kannada:{
        Welcome:'ನಿಮಗೆ ಸ್ವಾಗತ',
        Profile:'ಪ್ರೊಫೈಲ್',
        New:'ಹೊಸ',
        Connections:'ಸಂಪರ್ಕಗಳು',
        Requests:'ಕೋರಿಕೆಗಳು',
        Logout:'ಲಾಗ್ ಔಟ್',
        SaveProfile:'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
        Ignore:'ಅವಗಣಿಸು',
        Interested:'ಆಸಕ್ತಿ ಇದೆ',
        NoConnections:'ಯಾವುದೇ ಸಂಪರ್ಕಗಳು ಕಂಡುಬಂದಿಲ್ಲ!',
        NoRequests:'ಯಾವುದೇ ವಿನಂತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ!',
        NoNewUser:'ಯಾವುದೇ ಹೊಸ ಬಳಕೆದಾರರು ಕಂಡುಬಂದಿಲ್ಲ!',
        Reject:'ತಿರಸ್ಕರಿಸು',
        Accept:'ಸ್ವೀಕರಿಸು',
        EditProfile:'ಪ್ರೊಫೈಲ್ ತಿದ್ದುಪಡಿ',
        Login:'ಲಾಗಿನ್',
        successfully:'ಯಶಸ್ವಿಯಾಗಿದೆ',
        AccountCreated:'ಖಾತೆ ರಚಿಸಲಾಗಿದೆ',
        ProfileSaved :'ಪ್ರೊಫೈಲ್ Update',
        FirstName:'ಮೊದಲ ಹೆಸರು',
        LastName :'ಅಂತಿಮ ಹೆಸರು',
        PhotoURL:'ಫೋಟೋ URL',
        Age:'ವಯಸ್ಸು',
        Gender:'ಲಿಂಗ',
        Male:'ಪುರುಷ',
        Female:'ಮಹಿಳೆ ',
        Others:'ಇತರೆ',
        AboutMe:'ನನ್ನ ಬಗ್ಗೆ'
    },
    English:{
        Welcome:'Welcome',
        Profile:'Profile',
        New:'New',
        Connections:'Connections',
        Requests:'Requests',
        Logout:'Logout',
        SaveProfile:'Save Profile',
        Ignore:'Ignore',
        Interested:'Interested',
        NoConnections:'No connections found!',
        NoRequests:'No Requests found!',
        NoNewUser:'No new users found!',
        Reject:'Reject',
        Accept:'Accept',
        EditProfile:'Edit Profile',
        Login:'Login',
        successfully:'successfully.',
        AccountCreated:'Account created',
        ProfileSaved :'Profile saved',
        FirstName:'First Name',
        LastName :'Last Name',
        PhotoURL:'Photo URL',
        Age:'Age',
        Gender:'Gender',
        Male:'Male',
        Female:'Female',
        Others:'Others',
        AboutMe:'About me'
    },
     Hindi:{
        Welcome:'स्वागत',
        Profile:'प्रोफ़ाइल',
        New:'नया',
        Connections:'कनेक्शन',
        Requests:'निवेदन',
        Logout:'लॉगआउट',
        SaveProfile:'प्रोफ़ाइल सहेजें',
        Ignore:'उपेक्षा करना',
        Interested:'दिलचस्पी है',
        NoConnections:'कोई कनेक्शन नहीं मिला',
        NoRequests:'कोई रिक्वेस्ट नहीं मिली!',
        NoNewUser:'कोई नए उपयोगकर्ता नहीं मिले!',
        Reject:'इंकार करना',
        Accept:'स्वीकार करना',
        EditProfile:'प्रोफ़ाइल संपादित करें',
        Login:'लॉगइन',
        successfully:'सफलतापूर्वक',
        AccountCreated:'खाता बनाया गया',
        ProfileSaved :'प्रोफ़ाइल सहेजा गया',
        FirstName:'पहला नाम',
        LastName :'उपनाम',
        PhotoURL:'फ़ोटो URL',
        Age:'उम्र',
        Gender:'लिंग',
        Male:'पुरुष ',
        Female:'महिला',
        Others:'अन्य',
        AboutMe:'मेरे बारे में'
    },
}

export const SUPPORTED_LANGUAGES = ['Kannada', 'English','Hindi']